cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/yiran/ns-allinone-3.17/ns-3.17/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/yiran/ns-allinone-3.17/ns-3.17/.waf-1.7.10-4f6df1d839dc35640834d81573053140/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 33914640: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/home/yiran/ns-allinone-3.17/ns-3.17/build/.conf_check_bb4ab0a2da6fec0567ee396296163b23/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/libs\', \'-lpython2.7m\']\n'
